### ISSUE TITLE
Extract <wait.#> from commands and manually wait.

### ISSUE THREAD

**Issue by daemitus** [UnknownX7/QoLBar#10]
If you're already stealing from Anna, lets steal more :)

https://git.sr.ht/~jkcclemens/CCMM/tree/master/item/Macrology/MacroHandler.cs#L12

My current use case for this (botanist/miner switch button):
```
/macrolock
/macroerror off
/gearset change Botanist <wait.1>
/ac "Prospect" <wait.1>
/ac "Truth of Mountains" <wait.1>
/hudlayout 1
```

**Comment by UnknownX7** [comment]
Currently, I think its better to just leave it so people use MacroRecursion or Macrology to do this. I don't know if creating my own wait system that bypasses the built in one pushes it too far for XIVLauncher or not.
