### ISSUE TITLE
makes the button in Category type still has its own command?

### ISSUE THREAD

**Issue by peroperotina** [UnknownX7/QoLBar#12]
![image](https://user-images.githubusercontent.com/25301986/109733851-eb05d300-7bfa-11eb-8ff5-0a51eef3e92e.png)
For example, I wanna excute a frequently used command, I just click the button(the red one in the image above).  Just like a default command. In other situation, I wanna select one command in submenu when my mouse hover the button.

**Comment by UnknownX7** [comment]
So you want a category that also runs a command when opened?

**Comment by peroperotina** [comment]
> So you want a category that also runs a command when opened?

yes.

**Comment by UnknownX7** [comment]
fa8f9423b183b47191cd858e4239781e8b6fb48e
