### ISSUE TITLE
"Use Hotbar Frames on Icons" not working?

### ISSUE THREAD

**Issue by gucciBane** [UnknownX7/QoLBar#15]
Since patch 5.5, "Use Hotbar Frames on Icons" appears to do nothing.

**Comment by UnknownX7** [comment]
Probably TexTools related, a lot of people are reporting icons as missing, but it's only because the client failed to redownload them properly due to mods. There is currently a bug though that could cause it, but I don't think it can occur on the release version through normal means.

**Comment by gucciBane** [comment]
Oh yeah, I see just a couple missing. Funny.

But doing a Start Over again and reinstalling mods/Material UI fixed the hotbar frames issue. Thanks for the pointer!
