### ISSUE TITLE
Add pie rotation setting

### ISSUE THREAD

**Issue by Rauvagol** [UnknownX7/QoLBar#20]
For customization of the pie menu, would it be possible to add rotation offset slider or menu entry?

ie: currently with 4 bar entries, the pie "buttons" are located on the top left, top right, bottom left, and bottom right

with a rotation offset of 45 degrees, they would be located on the top, right, bottom, and left

an alternative idea would be the option to pick one of eight (cardinal/intercardinal) locations for the first "button" to be located, allowing for say, a 7 button bar having one button directly up from the center

**Comment by UnknownX7** [comment]
I've implemented a new default dynamic rotation for pies that always places the first button centered at the top. I feel like this is a good middle ground for now without having to add an individual option to each bar, but feel free to reopen this if you still want it.
