### ISSUE TITLE
Easier hotbar item reorganisation

### ISSUE THREAD

**Issue by PrincessRTFM** [UnknownX7/QoLBar#21]
At present, to reorganise the layout of a hotbar (or subcategory) you need to right click an item and hit the `↑` and `↓` button, which then closes the edit window, so you have to repeat that as many times as you want the item to move. It's workable, but tedious to move things more than a couple of spots, especially for large bars/categories. I had three ideas, presented here in order of increasing complexity and ease-of-use:

1) A modifier key (such as shift) that changes the "move one space" functionality to instead move to the indicated end. For example, holding shift and pressing the `↑` button would move the item to the first position in the bar/category.

2) A different modifier (eg, control) that keeps the edit window open, so that you can hold it down and click the arrow buttons several times in quick succession to move an item more than one position. Alternatively, maybe no modifier key but this becomes the new standard?

3) A drag-and-drop repositioning mechanic, which would obviously only work when the bar position is locked and would probably also need a toggle to enable it, so users don't accidentally move items. Preferably with real-time render updates, so you can make sure you get the items in the right places.

**Comment by UnknownX7** [comment]
See 48877806a46885a245da7fe71aa6e7216bde4e4a. I have already submitted the update, so it's just a matter of someone approving it. Additionally, an advanced editor is planned which will make editing bars/shortcuts much faster and easier.

**Comment by PrincessRTFM** [comment]
Oh cool! Sorry, I didn't look at recent commits, only issues.
