### ISSUE TITLE
Open-on-hover should close on cursor away

### ISSUE THREAD

**Issue by PrincessRTFM** [UnknownX7/QoLBar#23]
When a bar contains categories set to open on hover, it would be nice if moving the mouse _off_ of a category - especially onto another item on the bar - caused the opened category to close. For example, I have a teleports menu, where I click a bar button to open a list of teleports for use with `/tp`. Most of the items on that menu are categories for general areas, with subitems for the actual teleport (click teleport button -> hover `La Noscea...` -> click `Limsa Lominsa`, for instance) but there are a few that are direct. When I move my mouse off of the categories onto one of the direct locations (like `Return`, `Apartment`, `FC house`, or `Mor Dhona`), the subcategories stay open.

I realise this is hard to explain, so I can provide the actual exported teleport button if an example would make more sense.

**Comment by UnknownX7** [comment]
3a2a02c393fed1636bd69b46a29f9377589edb1f
