### ISSUE TITLE
[Request] Icon and/or name change on click

### ISSUE THREAD

**Issue by trowieuk** [UnknownX7/QoLBar#28]
Toggle an icon to greyscale/colour on click. Toggle between two names on click. 

For icon example I've got a few on/off toggles setup and would like the icon to greyscale for off, colour for on. 

As an example for toggling names, I have one command for toggling visibility of players and another for toggling battle effects, two separate buttons in QoL.
What I would like is to have the names do this... Hide Players On - when I click it change to - Hide Players Off. Same for toggling battle effects, Battle Effects On - when I click it change to - Battle Effects Off.

**Comment by UnknownX7** [comment]
This is possible using a category in incremental mode
