### ISSUE TITLE
[Suggestion]: Track cooldowns via plugin.

### ISSUE THREAD

**Issue by gamer4eg** [UnknownX7/QoLBar#29]
I immediately apologize for the fact that the text was generated by a google translator.

The fact that the only way to keep track of cooldowns is to put out a separate skillbar for this is frustrating to me.
You cannot click through it.
An ability can occasionally be clicked with the mouse pointer.
(Or you will be forever annoyed by the gear if you make a macro with an ability icon)
I would be very happy if you plan such functionality.
I know about the remindMe plugin, its appearance is terrible...

**Comment by UnknownX7** [comment]
5db64078811c267d4704dd4b5d62732c346867d5
Unsupported, but will be possible if you really want to. It wont be very easy to do and probably doesn't properly show charges at all.
