### ISSUE TITLE
Can we hide QoLBar during loading screens?

### ISSUE THREAD

**Issue by lunarwolfspirit** [UnknownX7/QoLBar#42]
Almost everything else in the UI is hidden apart from the chatbox. Is there an option I'm missing?

**Comment by UnknownX7** [comment]
Use condition sets,
![image](https://user-images.githubusercontent.com/12263784/141850479-b467c984-e69e-4b4b-b0b7-68572d2b1ed3.png)
then apply it to the bar 
![image](https://user-images.githubusercontent.com/12263784/141850569-76968441-178b-4f4f-a31b-37b32a2a7ef4.png)
