### ISSUE TITLE
Please raise the arbitrary "scale" limit to more than 2.0x

### ISSUE THREAD

**Issue by chaosblad3** [UnknownX7/QoLBar#44]
I am using Icons for several of my QoL bars for example my Job change menu and without significantly cranking up the global UI scale in dalamud settings, the buttons I've set up in QoL are still way too small even at a scale of 2.0x which is what you have set as an arbitrary limit.
![image](https://user-images.githubusercontent.com/4968222/145513477-bba1d487-c328-4cde-bbb3-6be66ed0d115.png)

Please raise the max scale limit to 3.0x or 4.0x at the very least, for both top level buttons and buttons inside a category!

**Comment by UnknownX7** [comment]
You can double click or control click on ImGui inputs to manually set it.
