### ISSUE TITLE
Eorzea Timespan not working

### ISSUE THREAD

**Issue by EEinders** [UnknownX7/QoLBar#47]
The Eorzea Timespan condition appears to only be returning 'True' if the span includes midnight, regardless of the actual time.

![image](https://user-images.githubusercontent.com/93601949/147862593-a6503834-4105-49a3-8ae1-282fcab14191.png)

![image](https://user-images.githubusercontent.com/93601949/147862594-cba68a0e-b1ad-431a-bf3b-6d7df75009bd.png)

![image](https://user-images.githubusercontent.com/93601949/147862596-90d223d3-1e6e-4020-b247-cf64a908b994.png)

![image](https://user-images.githubusercontent.com/93601949/147862598-04dd4157-7128-40c6-92c3-c37bc3408216.png)

**Comment by UnknownX7** [comment]
ee8767749b8073eac135328f2587e1a0b6dbe703
