### ISSUE TITLE
[Feature request] Hidden Hud conditional

### ISSUE THREAD

**Issue by Nikslg** [UnknownX7/QoLBar#57]
Unless I am mistaken, there is no "hud hidden" condition.
I doubt many people want to see QoLbar on their screenshot when they press Scroll Lock.

**Comment by UnknownX7** [comment]
This should be the default functionality in Dalamud, QoL Bar also has an setting to opt out of it as well.

![image](https://user-images.githubusercontent.com/12263784/163652687-66855087-6f93-4a40-bd54-5c8deb75b42c.png)
![image](https://user-images.githubusercontent.com/12263784/163652688-bc745c10-9b08-472c-8e0d-1b9688cbc781.png)
