### ISSUE TITLE
Some of the Conditions Flag not working

### ISSUE THREAD

**Issue by laik96** [UnknownX7/QoLBar#60]
The following Conditions Flag are not working;

- AutorunActive
- BeingMoved
- RolePlaying

I may be misinterpreting the flags, and if so, please clarify them for me. Thank you!

**Comment by bilenkonito** [comment]
Those are the game client's flags, they aren't a QoLBar exclusive feature.
For those three in particular:
- AutorunActive: Used in some MSQ duties that force you to walk as part of a in-world cinamatic
- BeingMoved: Used by some instance bosses that grab you
- RolePlaying: Used in Shadowbringers/Endwalker MSQ duties while you're playing as another character (e.g. when you're playing as Thancred)
