### ISSUE TITLE
Most recent update bars disappeared and config menu doesn't open

### ISSUE THREAD

**Issue by CToss** [UnknownX7/QoLBar#65]
when /qolconfig is invoked no bar appears, and all hotbars are gone

**Comment by Sirtristepan** [comment]
same here, just out of the blue

**Comment by CToss** [comment]
> same here, just out of the blue

Hey I just had to completely restart the game and it worked

**Comment by Sirtristepan** [comment]
didn't work for me..

**Comment by UnknownX7** [comment]
This is fixed in the next version, in the meantime you can disable Penumbra and then disable + enable QoLBar, then reenable Penumbra and it should be fixed even if relaunched.

**Comment by Sirtristepan** [comment]
oooh that worked, guess I'll have this noted if it happens again
