### ISSUE TITLE
[Bug Report] Icons not loading correctly

### ISSUE THREAD

**Issue by Lapidearum** [UnknownX7/QoLBar#67]
Upon booting the game and logging in, all of my QoL bar buttons with icons appear as a text button with an X on it. Uninstalling and reinstalling the plugin through Dalamud's plugin browser fixes the issue, but it would be nice to not have to do that every time.

**Comment by patsy158** [comment]
happened to me as well, but mine reinstalling wont fix it

**Comment by UnknownX7** [comment]
This should be fixed in the latest version.
