### ISSUE TITLE
The position of QoL bars dont update when XIV resolution changes

### ISSUE THREAD

**Issue by Ihellmasker** [UnknownX7/QoLBar#7]
When you change the resolution of your XIV window, the QoL bars don't update their positions, which can cause them to be offscreen.

For example, I use 1440p as my normal res with my QoLBar in the top right. When I switch to a smaller resolution the QoLBar doesn't adjust and is offscreen until I change the position of the bar then change it back in it's settings.

**Comment by UnknownX7** [comment]
ad6c744b066ada5bfbc11b54dd54d4a88f460df3
