### ISSUE TITLE
Icons not loading in, requires constant disable/enable in Dalamud

### ISSUE THREAD

**Issue by CToss** [UnknownX7/QoLBar#70]
More often than not, the icons won't load in on game launch, and require a disable/enable for the icons to come back, even as a temporary fix if we could have a refresh / command or something 
![image](https://user-images.githubusercontent.com/24399886/177861829-0a6311b5-3540-4fb2-a534-e4b662c3278d.png)

**Comment by Moonlight-Everlit** [comment]
Same thing on my end. Have to diable/enable multiple times per week due to icons disappearing.

**Comment by UnknownX7** [comment]
This should be fixed in the latest version.
