### ISSUE TITLE
Animation problems related to imgui changes

### ISSUE THREAD

**Issue by Fractura** [UnknownX7/QoLBar#71]
QoL Bar version: 2.3.0.5
Dalamud version: 6.4.0.33 net5 beta

When using the animation options slide or immediate, any buttons that are not part of the reveal area cause the bar to disappear without the associated command to be executed.

This is very likely to be related to the changes made to imgui in the current dalamud beta.

Steps to reproduce:
1. Add a hotbar with animation set to immediate or slide
2. Add a button with a command to execute, i.e. /xldev
3. Set reveal area scale to 0.0
4. Click the button created in 2.
Expected behavior: /xldev is executed (showing/hiding dalamud dev menu)
Actual behavior: hotbar disappears

Workaround:
- Set reveal area to 1.0 (but this renders buttons "behind" the area of the hotbar useless)
- Leave dalamud beta (confirmed working as intended on 6.4.0.31)

**Comment by UnknownX7** [comment]
Please reopen this if it is still occurring on the current Dalamud.
