### ISSUE TITLE
[Feature Request] Hide hotbar any time FFXIV would hide its normal hotbars.

### ISSUE THREAD

**Issue by Maguillage** [UnknownX7/QoLBar#77]
I styled mine as an extension to a normal hotbar and it feels a bit weird when I talk to certain NPCs (such as the retainer bell and the Limsa lift fellow) and all my hotbars hide except for the custom ones.

**Comment by UnknownX7** [comment]
This is doable via a condition set.
```
H4sIAAAAAAAACqtWUimpLEhVslJKVdJRSi5WsqqGiwB5Okp5QIZHfklSYpFCWGZxZlIOWJ2SVTSSOqBIJpBOLAMyEoGMeMfkksz8PKfEIqVaHaLUGRgChfKVrAyJVW9EonpjEtWbkKjelET1ZiSqNydRvQWJ6i1JUO9clF8MShpg9bG1OkplQDkjPWM9Iz1DpVoAa2rIFlICAAA=
```
You can import it here 
![image](https://user-images.githubusercontent.com/12263784/216733316-a279ae25-16eb-4661-9115-ba352dcbc8fe.png)

**Comment by Maguillage** [comment]
Ah. I assumed "addon visible" would be talking about things like the dalamud settings window, not stuff that came in the base game. Thanks for the settings to import.

I suppose that's a reason to close the issue, but I feel the option could have a more descriptive name.
