### ISSUE TITLE
Compatibility with GShade/ReShade

### ISSUE THREAD

**Issue by A-Sparowe** [UnknownX7/QoLBar#9]
While using GShade the QoLBar winds up being affected by whatever shaders are active for any given preset. The same thing used to happen with the user interface and HUD overlay in game as well. To mitigate this and prevent any UI or HUD elements from being affected by whatever it was GShade was doing at the time to change the overall look of the game itself you had to also have another plugin/shader active within GShade called "Keep UI / Restore UI". This would prevent any UI / HUD elements from having any undesirable effects. 

Since QoLBar is basically being treated as another part of the UI / HUD, at least from my point of view, it should also be given the option to benefit from what "Keep UI / Restore UI" is trying to do. I'm sure I'm not the only person who uses GShade or only uses it for screenshots either. I use it all the time to give the game itself a much needed boost in overall image quality. While I currently only have two different QoLBars activated, one for teleporting and one for job classes, their icons wind up either become too bright or too dark. Currently I have them set to "slide in" whenever my mouse cursor reaches the part of the screen where they are set to. Which is a real shame because I'd like to have them visible at all times. 

I also posted this issue in the GShade Discord.  A user replied with "Might not work, but try installing GShade to XIV a second time via the GShade Control Panel, but uncheck the alternative DirectX mode option." So I'm hoping this works. 

Really enjoy the QoLBar regardless of my issue. Hope you can help with this when given the time. Thanks.

**Comment by UnknownX7** [comment]
This is an issue with GShade/ReShade and Dalamud, I believe a Windows update broke it a few months ago (Not sure if this is true or not). Unfortunately, there's nothing I can do, but you can try asking in the Dalamud Discord/GitHub if there's a workaround available.

**Comment by A-Sparowe** [comment]
Ok thanks for letting me know.

**Comment by UnknownX7** [comment]
Appears to be fixed in the patch 5.5 version of Dalamud, so I'll close this for now unless something changes.
